In [0]:
import numpy as np

In [64]:
np.arange(6) # 1d array

array([0, 1, 2, 3, 4, 5])

In [2]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
np.arange(24).reshape(2.3.4)

SyntaxError: ignored

In [15]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
15
<type 'numpy.ndarray'>


In [0]:
a = np.array([(1,2,3,4), (5,6,7)])
print(a)

In [25]:
print(np.zeros( (3,4) ))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
print(np.ones( (2,3,4), dtype=np.int16 ))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [37]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [41]:
np.empty( (2,3,4) )

array([[[4.68251501e-310, 4.34573420e-114, 4.77166481e+180,
         7.62829054e+228],
        [2.91046314e-014, 5.98151350e-154, 4.26209407e+180,
         9.49439104e+170],
        [4.25109780e+228, 9.38038705e-154, 5.98157196e-154,
         2.31461741e-152]],

       [[3.44210185e+175, 1.02265713e-259, 2.91255304e-014,
         2.19993033e-152],
        [7.35161624e+223, 4.75685803e+063, 1.99721148e+161,
         7.26579621e+223],
        [2.13521628e+185, 2.66538997e-260, 4.94065646e-323,
         0.00000000e+000]]])

In [59]:
from numpy import pi
np.linspace(0,2,9) # 9 numbers from 0 to 2


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
f = np.sin(x)

In [61]:
np.arange(6)
np.arange

array([0, 1, 2, 3, 4, 5])

In [4]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

gpg: keybox '/tmp/tmpcxqnmejw/pubring.gpg' created
gpg: /tmp/tmpcxqnmejw/trustdb.gpg: trustdb created
gpg: key AD5F235DF639B041: public key "Launchpad PPA for Alessandro Strada" imported
gpg: Total number processed: 1
gpg:               imported: 1
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


Good for tutorial 
* https://docs.scipy.org/doc/numpy/user/quickstart.html
* https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d
* http://cs231n.github.io/python-numpy-tutorial/
* https://docs.python.org/3/tutorial/errors.html