[Click for the tutorial page](https://docs.scipy.org/doc/numpy/user/quickstart.html)

In [0]:
import numpy as np

In [73]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
a.shape

(3, 5)

In [75]:
a.ndim

2

In [76]:
a.dtype.name

'int64'

In [77]:
type(a)

numpy.ndarray

In [78]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [79]:
type(b)

numpy.ndarray

In [80]:
#Creat array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [82]:
c= np.array([ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [83]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [85]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [86]:
np.arange(20, 90, 17)

array([20, 37, 54, 71, 88])

In [87]:
np.arange(3, 100, 30)

array([ 3, 33, 63, 93])

In [88]:
a = np.array([0, 2.6, .5])
a

array([0. , 2.6, 0.5])

**There is differences between array and arange**

 * array 
 a = np.array([1,2,3,4])
 
 * arange
 a = np,arange(1,2,3,4)

In [0]:
from numpy import pi

In [90]:
np.linspace(0, 2, 9) # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [91]:
x = np.linspace(0, 2**pi, 100) # useful to evaluate function at lots of points
x

array([0.        , 0.08914119, 0.17828238, 0.26742357, 0.35656476,
       0.44570595, 0.53484714, 0.62398833, 0.71312952, 0.80227071,
       0.8914119 , 0.98055309, 1.06969428, 1.15883547, 1.24797666,
       1.33711785, 1.42625904, 1.51540023, 1.60454142, 1.69368261,
       1.7828238 , 1.87196499, 1.96110618, 2.05024737, 2.13938856,
       2.22852975, 2.31767094, 2.40681213, 2.49595332, 2.58509452,
       2.67423571, 2.7633769 , 2.85251809, 2.94165928, 3.03080047,
       3.11994166, 3.20908285, 3.29822404, 3.38736523, 3.47650642,
       3.56564761, 3.6547888 , 3.74392999, 3.83307118, 3.92221237,
       4.01135356, 4.10049475, 4.18963594, 4.27877713, 4.36791832,
       4.45705951, 4.5462007 , 4.63534189, 4.72448308, 4.81362427,
       4.90276546, 4.99190665, 5.08104784, 5.17018903, 5.25933022,
       5.34847141, 5.4376126 , 5.52675379, 5.61589498, 5.70503617,
       5.79417736, 5.88331855, 5.97245974, 6.06160093, 6.15074212,
       6.23988331, 6.3290245 , 6.41816569, 6.50730688, 6.59644

In [92]:
f = np.sin(x)
f

array([ 0.        ,  0.08902318,  0.17733944,  0.26424747,  0.34905713,
        0.43109497,  0.50970953,  0.58427655,  0.65420388,  0.71893626,
        0.77795964,  0.83080533,  0.87705368,  0.91633745,  0.94834467,
        0.9728212 ,  0.98957266,  0.99846603,  0.99943069,  0.99245898,
        0.97760626,  0.95499047,  0.92479121,  0.88724828,  0.84265981,
        0.79137987,  0.73381567,  0.67042432,  0.6017092 ,  0.52821598,
        0.45052825,  0.36926292,  0.28506531,  0.19860404,  0.11056567,
        0.02164931, -0.06743897, -0.15599172, -0.24330575, -0.32868773,
       -0.41145962, -0.49096417, -0.56657001, -0.63767679, -0.70371985,
       -0.76417474, -0.8185614 , -0.86644796, -0.90745415, -0.94125434,
       -0.96758014, -0.98622248, -0.99703334, -0.99992687, -0.99488008,
       -0.98193306, -0.96118862, -0.93281148, -0.89702699, -0.85411931,
       -0.80442915, -0.74835111, -0.6863305 , -0.61885981, -0.54647482,
       -0.46975033, -0.38929561, -0.30574954, -0.21977554, -0.13

In [102]:
a = np.arange(6)   # 1d aray
a

array([0, 1, 2, 3, 4, 5])

In [106]:
b = np.arange(12).reshape(4,3) # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
c = np.arange(24).reshape(2,3,4) # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [129]:
print(np.arange(10000)) # If array is to large, NumPy ll skips to print

[   0    1    2 ... 9997 9998 9999]


In [130]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
